// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class AccessApprovalRetry: AccessApprovalStub {
    let inner: any AccessApprovalStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any AccessApprovalStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listApprovalRequests(
      request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ListApprovalRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApprovalRequestsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.ListApprovalRequestsResponse
          in
          return try await self.inner.listApprovalRequests(request: r, options: o)
        })
    }

    public func getApprovalRequest(
      request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.ApprovalRequest
          in
          return try await self.inner.getApprovalRequest(request: r, options: o)
        })
    }

    public func approveApprovalRequest(
      request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ApproveApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.ApprovalRequest
          in
          return try await self.inner.approveApprovalRequest(request: r, options: o)
        })
    }

    public func dismissApprovalRequest(
      request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DismissApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.ApprovalRequest
          in
          return try await self.inner.dismissApprovalRequest(request: r, options: o)
        })
    }

    public func invalidateApprovalRequest(
      request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: InvalidateApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.ApprovalRequest
          in
          return try await self.inner.invalidateApprovalRequest(request: r, options: o)
        })
    }

    public func getAccessApprovalSettings(
      request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalSettings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.AccessApprovalSettings
          in
          return try await self.inner.getAccessApprovalSettings(request: r, options: o)
        })
    }

    public func updateAccessApprovalSettings(
      request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalSettings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.AccessApprovalSettings
          in
          return try await self.inner.updateAccessApprovalSettings(request: r, options: o)
        })
    }

    public func deleteAccessApprovalSettings(
      request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteAccessApprovalSettings(request: r, options: o)
        })
    }

    public func getAccessApprovalServiceAccount(
      request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAccessApprovalServiceAccountMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessApprovalV1.AccessApprovalServiceAccount
          in
          return try await self.inner.getAccessApprovalServiceAccount(request: r, options: o)
        })
    }
  }
}
