// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Home office and physical location of the principal.
public struct AccessLocations: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The "home office" location of the principal. A two-letter country code
  /// (ISO 3166-1 alpha-2), such as "US", "DE" or "GB" or a region code. In some
  /// limited situations Google systems may refer refer to a region code instead
  /// of a country code.
  /// Possible Region Codes:
  ///
  ///   * ASI: Asia
  ///   * EUR: Europe
  ///   * OCE: Oceania
  ///   * AFR: Africa
  ///   * NAM: North America
  ///   * SAM: South America
  ///   * ANT: Antarctica
  ///   * ANY: Any location
  public var principalOfficeCountry: Swift.String = Swift.String()

  /// Physical location of the principal at the time of the access. A
  /// two-letter country code (ISO 3166-1 alpha-2), such as "US", "DE" or "GB" or
  /// a region code. In some limited situations Google systems may refer refer to
  /// a region code instead of a country code.
  /// Possible Region Codes:
  ///
  ///   * ASI: Asia
  ///   * EUR: Europe
  ///   * OCE: Oceania
  ///   * AFR: Africa
  ///   * NAM: North America
  ///   * SAM: South America
  ///   * ANT: Antarctica
  ///   * ANY: Any location
  public var principalPhysicalLocationCountry: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccessLocations`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessLocations().with { $0.principalOfficeCountry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let principalOfficeCountry = CodingKeys(stringValue: "principalOfficeCountry")
    static let principalPhysicalLocationCountry = CodingKeys(
      stringValue: "principalPhysicalLocationCountry")

    static let _knownKeys: Set<Swift.String> = [
      "principalOfficeCountry",
      "principalPhysicalLocationCountry",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .principalOfficeCountry)
    {
      self.principalOfficeCountry = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .principalPhysicalLocationCountry)
    {
      self.principalPhysicalLocationCountry = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.principalOfficeCountry, forKey: .principalOfficeCountry)
    try container.encode(
      self.principalPhysicalLocationCountry, forKey: .principalPhysicalLocationCountry)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.AccessLocations"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
