// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AccessApprovalLogging: AccessApprovalStub {
    let inner: any AccessApprovalStub
    let logger: Logger

    public init(_ inner: any AccessApprovalStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudAccessapprovalV1"
      logger[metadataKey: "gcp.client.service"] = "accessapproval"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AccessApproval"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listApprovalRequests(
      request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listApprovalRequests",
        action: {
          (r: ListApprovalRequestsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse
          in
          return try await self.inner.listApprovalRequests(request: r, options: o)
        })
    }

    public func getApprovalRequest(
      request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        name: "getApprovalRequest",
        action: {
          (r: GetApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.ApprovalRequest
          in
          return try await self.inner.getApprovalRequest(request: r, options: o)
        })
    }

    public func approveApprovalRequest(
      request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        name: "approveApprovalRequest",
        action: {
          (r: ApproveApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.ApprovalRequest
          in
          return try await self.inner.approveApprovalRequest(request: r, options: o)
        })
    }

    public func dismissApprovalRequest(
      request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        name: "dismissApprovalRequest",
        action: {
          (r: DismissApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.ApprovalRequest
          in
          return try await self.inner.dismissApprovalRequest(request: r, options: o)
        })
    }

    public func invalidateApprovalRequest(
      request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
      try await self._intercept(
        request: request,
        options: options,
        name: "invalidateApprovalRequest",
        action: {
          (r: InvalidateApprovalRequestMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.ApprovalRequest
          in
          return try await self.inner.invalidateApprovalRequest(request: r, options: o)
        })
    }

    public func getAccessApprovalSettings(
      request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAccessApprovalSettings",
        action: {
          (r: GetAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.AccessApprovalSettings
          in
          return try await self.inner.getAccessApprovalSettings(request: r, options: o)
        })
    }

    public func updateAccessApprovalSettings(
      request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAccessApprovalSettings",
        action: {
          (r: UpdateAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.AccessApprovalSettings
          in
          return try await self.inner.updateAccessApprovalSettings(request: r, options: o)
        })
    }

    public func deleteAccessApprovalSettings(
      request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAccessApprovalSettings",
        action: {
          (r: DeleteAccessApprovalSettingsMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteAccessApprovalSettings(request: r, options: o)
        })
    }

    public func getAccessApprovalServiceAccount(
      request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAccessApprovalServiceAccount",
        action: {
          (r: GetAccessApprovalServiceAccountMessage, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount
          in
          return try await self.inner.getAccessApprovalServiceAccount(request: r, options: o)
        })
    }
  }
}
