// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// This API allows a customer to manage accesses to cloud resources by
/// Google personnel. It defines the following resource model:
///
/// - The API has a collection of
///   [ApprovalRequest][google.cloud.accessapproval.v1.ApprovalRequest]
///   resources, named `approvalRequests/{approval_request}`
/// - The API has top-level settings per Project/Folder/Organization, named
///   `accessApprovalSettings`
///
/// The service also periodically emails a list of recipients, defined at the
/// Project/Folder/Organization level in the accessApprovalSettings, when there
/// is a pending ApprovalRequest for them to act on. The ApprovalRequests can
/// also optionally be published to a Pub/Sub topic owned by the customer
/// (contact support if you would like to enable Pub/Sub notifications).
///
/// ApprovalRequests can be approved or dismissed. Google personnel can only
/// access the indicated resource or resources if the request is approved
/// (subject to some exclusions:
/// https://cloud.google.com/access-approval/docs/overview#exclusions).
///
/// Note: Using Access Approval functionality will mean that Google may not be
/// able to meet the SLAs for your chosen products, as any support response times
/// may be dramatically increased. As such the SLAs do not apply to any service
/// disruption to the extent impacted by Customer's use of Access Approval. Do
/// not enable Access Approval for projects where you may require high service
/// availability and rapid response by Google Cloud Support.
///
/// After a request is approved or dismissed, no further action may be taken on
/// it. Requests with the requested_expiration in the past or with no activity
/// for 14 days are considered dismissed. When an approval expires, the request
/// is considered dismissed.
///
/// If a request is not approved or dismissed, we call it pending.
///
/// [google.cloud.accessapproval.v1.ApprovalRequest]: <doc:ApprovalRequest>
///
/// @Snippet(path: "AccessApprovalQuickstart")
public class AccessApprovalClient: Clients.AccessApprovalProtocol {
  let inner: any Clients.AccessApprovalStub

  /// Creates a new `AccessApprovalClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AccessApprovalStub = try Clients.AccessApprovalTransport(options)
    inner = Clients.AccessApprovalRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AccessApprovalLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists approval requests associated with a project, folder, or organization.
  /// Approval requests can be filtered by state (pending, active, dismissed).
  /// The order is reverse chronological.
  ///
  /// @Snippet(path: "AccessApproval_ListApprovalRequests")
  public func listApprovalRequests(
    request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse {
    try await self.inner.listApprovalRequests(request: request, options: options)
  }

  /// Lists approval requests associated with a project, folder, or organization.
  /// Approval requests can be filtered by state (pending, active, dismissed).
  /// The order is reverse chronological.
  ///
  /// @Snippet(path: "AccessApproval_ListApprovalRequests")
  public func listApprovalRequests(
    byItem: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listApprovalRequests(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets an approval request. Returns NOT_FOUND if the request does not exist.
  ///
  /// @Snippet(path: "AccessApproval_GetApprovalRequest")
  public func getApprovalRequest(
    request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    try await self.inner.getApprovalRequest(request: request, options: options)
  }

  /// Approves a request and returns the updated ApprovalRequest.
  ///
  /// Returns NOT_FOUND if the request does not exist. Returns
  /// FAILED_PRECONDITION if the request exists but is not in a pending state.
  ///
  /// @Snippet(path: "AccessApproval_ApproveApprovalRequest")
  public func approveApprovalRequest(
    request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    try await self.inner.approveApprovalRequest(request: request, options: options)
  }

  /// Dismisses a request. Returns the updated ApprovalRequest.
  ///
  /// NOTE: This does not deny access to the resource if another request has been
  /// made and approved. It is equivalent in effect to ignoring the request
  /// altogether.
  ///
  /// Returns NOT_FOUND if the request does not exist.
  ///
  /// Returns FAILED_PRECONDITION if the request exists but is not in a pending
  /// state.
  ///
  /// @Snippet(path: "AccessApproval_DismissApprovalRequest")
  public func dismissApprovalRequest(
    request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    try await self.inner.dismissApprovalRequest(request: request, options: options)
  }

  /// Invalidates an existing ApprovalRequest. Returns the updated
  /// ApprovalRequest.
  ///
  /// NOTE: This does not deny access to the resource if another request has been
  /// made and approved. It only invalidates a single approval.
  ///
  /// Returns FAILED_PRECONDITION if the request exists but is not in an approved
  /// state.
  ///
  /// @Snippet(path: "AccessApproval_InvalidateApprovalRequest")
  public func invalidateApprovalRequest(
    request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    try await self.inner.invalidateApprovalRequest(request: request, options: options)
  }

  /// Gets the settings associated with a project, folder, or organization.
  ///
  /// @Snippet(path: "AccessApproval_GetAccessApprovalSettings")
  public func getAccessApprovalSettings(
    request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    try await self.inner.getAccessApprovalSettings(request: request, options: options)
  }

  /// Updates the settings associated with a project, folder, or organization.
  /// Settings to update are determined by the value of field_mask.
  ///
  /// @Snippet(path: "AccessApproval_UpdateAccessApprovalSettings")
  public func updateAccessApprovalSettings(
    request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    try await self.inner.updateAccessApprovalSettings(request: request, options: options)
  }

  /// Deletes the settings associated with a project, folder, or organization.
  /// This will have the effect of disabling Access Approval for the project,
  /// folder, or organization, but only if all ancestors also have Access
  /// Approval disabled. If Access Approval is enabled at a higher level of the
  /// hierarchy, then Access Approval will still be enabled at this level as
  /// the settings are inherited.
  ///
  /// @Snippet(path: "AccessApproval_DeleteAccessApprovalSettings")
  public func deleteAccessApprovalSettings(
    request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAccessApprovalSettings(request: request, options: options)
  }

  /// Retrieves the service account that is used by Access Approval to access KMS
  /// keys for signing approved approval requests.
  ///
  /// @Snippet(path: "AccessApproval_GetAccessApprovalServiceAccount")
  public func getAccessApprovalServiceAccount(
    request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount {
    try await self.inner.getAccessApprovalServiceAccount(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AccessApprovalClient`.
  ///
  /// To mock `AccessApprovalClient` change your functions to receive
  /// `some AccessApprovalProtocol` or `any AccessApprovalProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AccessApprovalProtocol {
    /// See `AccessApprovalClient.listApprovalRequests`.
    func listApprovalRequests(request: ListApprovalRequestsMessage) async throws
      -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse

    /// See `AccessApprovalClient.listApprovalRequests`.
    func listApprovalRequests(
      byItem: ListApprovalRequestsMessage
    ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error>

    /// See `AccessApprovalClient.listApprovalRequests`.
    func listApprovalRequests(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error>

    /// See `AccessApprovalClient.getApprovalRequest`.
    func getApprovalRequest(request: GetApprovalRequestMessage) async throws
      -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.getApprovalRequest`.
    func getApprovalRequest(
      name: Swift.String,
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.approveApprovalRequest`.
    func approveApprovalRequest(request: ApproveApprovalRequestMessage) async throws
      -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.dismissApprovalRequest`.
    func dismissApprovalRequest(request: DismissApprovalRequestMessage) async throws
      -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.invalidateApprovalRequest`.
    func invalidateApprovalRequest(request: InvalidateApprovalRequestMessage) async throws
      -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.getAccessApprovalSettings`.
    func getAccessApprovalSettings(request: GetAccessApprovalSettingsMessage) async throws
      -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.getAccessApprovalSettings`.
    func getAccessApprovalSettings(
      name: Swift.String,
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.updateAccessApprovalSettings`.
    func updateAccessApprovalSettings(request: UpdateAccessApprovalSettingsMessage) async throws
      -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.updateAccessApprovalSettings`.
    func updateAccessApprovalSettings(
      settings: AccessApprovalSettings?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.deleteAccessApprovalSettings`.
    func deleteAccessApprovalSettings(request: DeleteAccessApprovalSettingsMessage) async throws

    /// See `AccessApprovalClient.deleteAccessApprovalSettings`.
    func deleteAccessApprovalSettings(
      name: Swift.String,
    ) async throws

    /// See `AccessApprovalClient.getAccessApprovalServiceAccount`.
    func getAccessApprovalServiceAccount(request: GetAccessApprovalServiceAccountMessage)
      async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount

    /// See `AccessApprovalClient.getAccessApprovalServiceAccount`.
    func getAccessApprovalServiceAccount(
      name: Swift.String,
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount

    /// See `AccessApprovalClient.listApprovalRequests`.
    func listApprovalRequests(
      request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse

    /// See `AccessApprovalClient.listApprovalRequests`.
    func listApprovalRequests(
      byItem: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error>

    /// See `AccessApprovalClient.getApprovalRequest`.
    func getApprovalRequest(
      request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.approveApprovalRequest`.
    func approveApprovalRequest(
      request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.dismissApprovalRequest`.
    func dismissApprovalRequest(
      request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.invalidateApprovalRequest`.
    func invalidateApprovalRequest(
      request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest

    /// See `AccessApprovalClient.getAccessApprovalSettings`.
    func getAccessApprovalSettings(
      request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.updateAccessApprovalSettings`.
    func updateAccessApprovalSettings(
      request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings

    /// See `AccessApprovalClient.deleteAccessApprovalSettings`.
    func deleteAccessApprovalSettings(
      request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AccessApprovalClient.getAccessApprovalServiceAccount`.
    func getAccessApprovalServiceAccount(
      request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount
  }
}

// Default implementations
extension Clients.AccessApprovalProtocol {
  public func listApprovalRequests(request: ListApprovalRequestsMessage) async throws
    -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse
  {
    try await self.listApprovalRequests(request: request, options: .init())
  }

  public func listApprovalRequests(
    request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listApprovalRequests(
    byItem: ListApprovalRequestsMessage
  ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error> {
    try self.listApprovalRequests(byItem: byItem, options: .init())
  }

  public func listApprovalRequests(
    byItem: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAccessapprovalV1.ListApprovalRequestsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApprovalRequests(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ApprovalRequest, Swift.Error> {
    let request = ListApprovalRequestsMessage().with {
      $0.parent = parent
    }
    return try self.listApprovalRequests(byItem: request)
  }

  public func getApprovalRequest(request: GetApprovalRequestMessage) async throws
    -> GoogleCloudAccessapprovalV1.ApprovalRequest
  {
    try await self.getApprovalRequest(request: request, options: .init())
  }

  public func getApprovalRequest(
    request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getApprovalRequest(
    name: Swift.String,
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    let request = GetApprovalRequestMessage().with {
      $0.name = name
    }
    return try await self.getApprovalRequest(request: request)
  }

  public func approveApprovalRequest(request: ApproveApprovalRequestMessage) async throws
    -> GoogleCloudAccessapprovalV1.ApprovalRequest
  {
    try await self.approveApprovalRequest(request: request, options: .init())
  }

  public func approveApprovalRequest(
    request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func dismissApprovalRequest(request: DismissApprovalRequestMessage) async throws
    -> GoogleCloudAccessapprovalV1.ApprovalRequest
  {
    try await self.dismissApprovalRequest(request: request, options: .init())
  }

  public func dismissApprovalRequest(
    request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func invalidateApprovalRequest(request: InvalidateApprovalRequestMessage) async throws
    -> GoogleCloudAccessapprovalV1.ApprovalRequest
  {
    try await self.invalidateApprovalRequest(request: request, options: .init())
  }

  public func invalidateApprovalRequest(
    request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.ApprovalRequest {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAccessApprovalSettings(request: GetAccessApprovalSettingsMessage) async throws
    -> GoogleCloudAccessapprovalV1.AccessApprovalSettings
  {
    try await self.getAccessApprovalSettings(request: request, options: .init())
  }

  public func getAccessApprovalSettings(
    request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAccessApprovalSettings(
    name: Swift.String,
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    let request = GetAccessApprovalSettingsMessage().with {
      $0.name = name
    }
    return try await self.getAccessApprovalSettings(request: request)
  }

  public func updateAccessApprovalSettings(request: UpdateAccessApprovalSettingsMessage)
    async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings
  {
    try await self.updateAccessApprovalSettings(request: request, options: .init())
  }

  public func updateAccessApprovalSettings(
    request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAccessApprovalSettings(
    settings: AccessApprovalSettings?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalSettings {
    let request = UpdateAccessApprovalSettingsMessage().with {
      $0.settings = settings
      $0.updateMask = updateMask
    }
    return try await self.updateAccessApprovalSettings(request: request)
  }

  public func deleteAccessApprovalSettings(request: DeleteAccessApprovalSettingsMessage)
    async throws
  {
    try await self.deleteAccessApprovalSettings(request: request, options: .init())
  }

  public func deleteAccessApprovalSettings(
    request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAccessApprovalSettings(
    name: Swift.String,
  ) async throws {
    let request = DeleteAccessApprovalSettingsMessage().with {
      $0.name = name
    }
    try await self.deleteAccessApprovalSettings(request: request)
  }

  public func getAccessApprovalServiceAccount(request: GetAccessApprovalServiceAccountMessage)
    async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount
  {
    try await self.getAccessApprovalServiceAccount(request: request, options: .init())
  }

  public func getAccessApprovalServiceAccount(
    request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAccessApprovalServiceAccount(
    name: Swift.String,
  ) async throws -> GoogleCloudAccessapprovalV1.AccessApprovalServiceAccount {
    let request = GetAccessApprovalServiceAccountMessage().with {
      $0.name = name
    }
    return try await self.getAccessApprovalServiceAccount(request: request)
  }
}
