// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Home office and physical location of the principal.
public struct AccessLocations: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The "home office" location of the principal. A two-letter country code
  /// (ISO 3166-1 alpha-2), such as "US", "DE" or "GB" or a region code. In some
  /// limited situations Google systems may refer refer to a region code instead
  /// of a country code.
  /// Possible Region Codes:
  ///
  ///   * ASI: Asia
  ///   * EUR: Europe
  ///   * OCE: Oceania
  ///   * AFR: Africa
  ///   * NAM: North America
  ///   * SAM: South America
  ///   * ANT: Antarctica
  ///   * ANY: Any location
  public var principalOfficeCountry: Swift.String = Swift.String()

  /// Physical location of the principal at the time of the access. A
  /// two-letter country code (ISO 3166-1 alpha-2), such as "US", "DE" or "GB" or
  /// a region code. In some limited situations Google systems may refer refer to
  /// a region code instead of a country code.
  /// Possible Region Codes:
  ///
  ///   * ASI: Asia
  ///   * EUR: Europe
  ///   * OCE: Oceania
  ///   * AFR: Africa
  ///   * NAM: North America
  ///   * SAM: South America
  ///   * ANT: Antarctica
  ///   * ANY: Any location
  public var principalPhysicalLocationCountry: Swift.String = Swift.String()

  /// Initialize a new instance of `AccessLocations`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessLocations().with { $0.principalOfficeCountry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.AccessLocations"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
