// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol AccessApprovalStub: Sendable {
    func listApprovalRequests(
      request: ListApprovalRequestsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ListApprovalRequestsResponse

    func getApprovalRequest(
      request: GetApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest

    func approveApprovalRequest(
      request: ApproveApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest

    func dismissApprovalRequest(
      request: DismissApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest

    func invalidateApprovalRequest(
      request: InvalidateApprovalRequestMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.ApprovalRequest

    func getAccessApprovalSettings(
      request: GetAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalSettings

    func updateAccessApprovalSettings(
      request: UpdateAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalSettings

    func deleteAccessApprovalSettings(
      request: DeleteAccessApprovalSettingsMessage, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getAccessApprovalServiceAccount(
      request: GetAccessApprovalServiceAccountMessage, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAccessApprovalV1.AccessApprovalServiceAccount
  }
}
