// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request for the customer to approve access to a resource.
public struct ApprovalRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the request. Format is
  /// "{projects|folders|organizations}/{id}/approvalRequests/{approval_request}".
  public var name: Swift.String = Swift.String()

  /// The resource for which approval is being requested. The format of the
  /// resource name is defined at
  /// https://cloud.google.com/apis/design/resource_names. The resource name here
  /// may either be a "full" resource name (e.g.
  /// "//library.googleapis.com/shelves/shelf1/books/book2") or a "relative"
  /// resource name (e.g. "shelves/shelf1/books/book2") as described in the
  /// resource name specification.
  public var requestedResourceName: Swift.String = Swift.String()

  /// Properties related to the resource represented by requested_resource_name.
  public var requestedResourceProperties: ResourceProperties? = nil

  /// The justification for which approval is being requested.
  public var requestedReason: AccessReason? = nil

  /// The locations for which approval is being requested.
  public var requestedLocations: AccessLocations? = nil

  /// The time at which approval was requested.
  public var requestTime: GoogleWKT.WKTTimestamp? = nil

  /// The requested expiration for the approval. If the request is approved,
  /// access will be granted from the time of approval until the expiration time.
  public var requestedExpiration: GoogleWKT.WKTTimestamp? = nil

  /// The current decision on the approval request.
  public var decision: OneOf_Decision? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApprovalRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApprovalRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let requestedResourceName = CodingKeys(stringValue: "requestedResourceName")
    static let requestedResourceProperties = CodingKeys(stringValue: "requestedResourceProperties")
    static let requestedReason = CodingKeys(stringValue: "requestedReason")
    static let requestedLocations = CodingKeys(stringValue: "requestedLocations")
    static let requestTime = CodingKeys(stringValue: "requestTime")
    static let requestedExpiration = CodingKeys(stringValue: "requestedExpiration")
    static let approve = CodingKeys(stringValue: "approve")
    static let dismiss = CodingKeys(stringValue: "dismiss")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "requestedResourceName",
      "requestedResourceProperties",
      "requestedReason",
      "requestedLocations",
      "requestTime",
      "requestedExpiration",
      "approve",
      "dismiss",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestedResourceName)
    {
      self.requestedResourceName = value
    }
    self.requestedResourceProperties = try container.decodeIfPresent(
      ResourceProperties.self, forKey: .requestedResourceProperties)
    self.requestedReason = try container.decodeIfPresent(
      AccessReason.self, forKey: .requestedReason)
    self.requestedLocations = try container.decodeIfPresent(
      AccessLocations.self, forKey: .requestedLocations)
    self.requestTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .requestTime)
    self.requestedExpiration = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .requestedExpiration)

    var decision: OneOf_Decision? = nil
    let decisionCheckAndSet = {
      if decision != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'decision'"))
      }
      decision = $0
    }
    if let approve = try container.decodeIfPresent(ApproveDecision?.self, forKey: .approve) {
      try decisionCheckAndSet(.approve(approve))
    }
    if let dismiss = try container.decodeIfPresent(DismissDecision?.self, forKey: .dismiss) {
      try decisionCheckAndSet(.dismiss(dismiss))
    }
    self.decision = decision
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestedResourceName, forKey: .requestedResourceName)
    try container.encodeIfPresent(
      self.requestedResourceProperties, forKey: .requestedResourceProperties)
    try container.encodeIfPresent(self.requestedReason, forKey: .requestedReason)
    try container.encodeIfPresent(self.requestedLocations, forKey: .requestedLocations)
    try container.encodeIfPresent(self.requestTime, forKey: .requestTime)
    try container.encodeIfPresent(self.requestedExpiration, forKey: .requestedExpiration)

    if let choice = self.decision {
      switch choice {
      case .approve(let value):
        try container.encode(value, forKey: .approve)
      case .dismiss(let value):
        try container.encode(value, forKey: .dismiss)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The current decision on the approval request.
  public enum OneOf_Decision: Codable, Equatable, Sendable {
    /// Access was approved.
    indirect case approve(ApproveDecision?)
    /// The request was dismissed.
    indirect case dismiss(DismissDecision?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.ApprovalRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
