// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A decision that has been made to approve access to a resource.
public struct ApproveDecision: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The time at which approval was granted.
  public var approveTime: GoogleCloudWKT.Timestamp? = nil

  /// The time at which the approval expires.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// If set, denotes the timestamp at which the approval is invalidated.
  public var invalidateTime: GoogleCloudWKT.Timestamp? = nil

  /// The signature for the ApprovalRequest and details on how it was signed.
  public var signatureInfo: SignatureInfo? = nil

  /// True when the request has been auto-approved.
  public var autoApproved: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ApproveDecision`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApproveDecision().with { $0.approveTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.ApproveDecision"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
