// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A decision that has been made to approve access to a resource.
public struct ApproveDecision: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time at which approval was granted.
  public var approveTime: GoogleWKT.Timestamp? = nil

  /// The time at which the approval expires.
  public var expireTime: GoogleWKT.Timestamp? = nil

  /// If set, denotes the timestamp at which the approval is invalidated.
  public var invalidateTime: GoogleWKT.Timestamp? = nil

  /// The signature for the ApprovalRequest and details on how it was signed.
  public var signatureInfo: SignatureInfo? = nil

  /// True when the request has been auto-approved.
  public var autoApproved: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApproveDecision`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApproveDecision().with { $0.approveTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let approveTime = CodingKeys(stringValue: "approveTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let invalidateTime = CodingKeys(stringValue: "invalidateTime")
    static let signatureInfo = CodingKeys(stringValue: "signatureInfo")
    static let autoApproved = CodingKeys(stringValue: "autoApproved")

    static let _knownKeys: Set<Swift.String> = [
      "approveTime",
      "expireTime",
      "invalidateTime",
      "signatureInfo",
      "autoApproved",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.approveTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .approveTime)
    self.expireTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .expireTime)
    self.invalidateTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .invalidateTime)
    self.signatureInfo = try container.decodeIfPresent(SignatureInfo.self, forKey: .signatureInfo)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoApproved) {
      self.autoApproved = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.approveTime, forKey: .approveTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encodeIfPresent(self.invalidateTime, forKey: .invalidateTime)
    try container.encodeIfPresent(self.signatureInfo, forKey: .signatureInfo)
    try container.encode(self.autoApproved, forKey: .autoApproved)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.ApproveDecision"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
