// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents the enrollment of a cloud resource into a specific service.
public struct EnrolledService: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The product for which Access Approval will be enrolled. Allowed values are
  /// listed below (case-sensitive):
  ///
  ///   * all
  ///   * GA
  ///   * App Engine
  ///   * BigQuery
  ///   * Cloud Bigtable
  ///   * Cloud Key Management Service
  ///   * Compute Engine
  ///   * Cloud Dataflow
  ///   * Cloud Dataproc
  ///   * Cloud DLP
  ///   * Cloud EKM
  ///   * Cloud HSM
  ///   * Cloud Identity and Access Management
  ///   * Cloud Logging
  ///   * Cloud Pub/Sub
  ///   * Cloud Spanner
  ///   * Cloud SQL
  ///   * Cloud Storage
  ///   * Google Kubernetes Engine
  ///   * Organization Policy Serivice
  ///   * Persistent Disk
  ///   * Resource Manager
  ///   * Secret Manager
  ///   * Speaker ID
  ///
  /// Note: These values are supported as input for legacy purposes, but will not
  /// be returned from the API.
  ///
  ///   * all
  ///   * ga-only
  ///   * appengine.googleapis.com
  ///   * bigquery.googleapis.com
  ///   * bigtable.googleapis.com
  ///   * container.googleapis.com
  ///   * cloudkms.googleapis.com
  ///   * cloudresourcemanager.googleapis.com
  ///   * cloudsql.googleapis.com
  ///   * compute.googleapis.com
  ///   * dataflow.googleapis.com
  ///   * dataproc.googleapis.com
  ///   * dlp.googleapis.com
  ///   * iam.googleapis.com
  ///   * logging.googleapis.com
  ///   * orgpolicy.googleapis.com
  ///   * pubsub.googleapis.com
  ///   * spanner.googleapis.com
  ///   * secretmanager.googleapis.com
  ///   * speakerid.googleapis.com
  ///   * storage.googleapis.com
  ///
  /// Calls to UpdateAccessApprovalSettings using 'all' or any of the
  /// XXX.googleapis.com will be translated to the associated product name
  /// ('all', 'App Engine', etc.).
  ///
  /// Note: 'all' will enroll the resource in all products supported at both 'GA'
  /// and 'Preview' levels.
  ///
  /// More information about levels of support is available at
  /// https://cloud.google.com/access-approval/docs/supported-services
  public var cloudProduct: Swift.String = Swift.String()

  /// The enrollment level of the service.
  public var enrollmentLevel: EnrollmentLevel = EnrollmentLevel()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EnrolledService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EnrolledService().with { $0.cloudProduct = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudProduct = CodingKeys(stringValue: "cloudProduct")
    static let enrollmentLevel = CodingKeys(stringValue: "enrollmentLevel")

    static let _knownKeys: Set<Swift.String> = [
      "cloudProduct",
      "enrollmentLevel",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudProduct) {
      self.cloudProduct = value
    }
    if let value = try container.decodeIfPresent(EnrollmentLevel.self, forKey: .enrollmentLevel) {
      self.enrollmentLevel = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cloudProduct, forKey: .cloudProduct)
    try container.encode(self.enrollmentLevel, forKey: .enrollmentLevel)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.EnrolledService"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
