// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about the digital signature of the resource.
public struct SignatureInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The digital signature.
  public var signature: Foundation.Data = Foundation.Data()

  /// How this signature may be verified.
  public var verificationInfo: OneOf_VerificationInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SignatureInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SignatureInfo().with { $0.signature = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let signature = CodingKeys(stringValue: "signature")
    static let googlePublicKeyPem = CodingKeys(stringValue: "googlePublicKeyPem")
    static let customerKmsKeyVersion = CodingKeys(stringValue: "customerKmsKeyVersion")

    static let _knownKeys: Set<Swift.String> = [
      "signature",
      "googlePublicKeyPem",
      "customerKmsKeyVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .signature) {
      self.signature = value
    }

    var verificationInfo: OneOf_VerificationInfo? = nil
    let verificationInfoCheckAndSet = {
      if verificationInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'verificationInfo'"))
      }
      verificationInfo = $0
    }
    if let googlePublicKeyPem = try container.decodeIfPresent(
      Swift.String.self, forKey: .googlePublicKeyPem)
    {
      try verificationInfoCheckAndSet(.googlePublicKeyPem(googlePublicKeyPem))
    }
    if let customerKmsKeyVersion = try container.decodeIfPresent(
      Swift.String.self, forKey: .customerKmsKeyVersion)
    {
      try verificationInfoCheckAndSet(.customerKmsKeyVersion(customerKmsKeyVersion))
    }
    self.verificationInfo = verificationInfo
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.signature, forKey: .signature)

    if let choice = self.verificationInfo {
      switch choice {
      case .googlePublicKeyPem(let value):
        try container.encode(value, forKey: .googlePublicKeyPem)
      case .customerKmsKeyVersion(let value):
        try container.encode(value, forKey: .customerKmsKeyVersion)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// How this signature may be verified.
  public enum OneOf_VerificationInfo: Codable, Equatable, Sendable {
    /// The public key for the Google default signing, encoded in PEM format. The
    /// signature was created using a private key which may be verified using
    /// this public key.
    case googlePublicKeyPem(Swift.String)
    /// The resource name of the customer CryptoKeyVersion used for signing.
    case customerKmsKeyVersion(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.accessapproval.v1.SignatureInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
